### ISSUE TITLE
crash when choosing add device

### ISSUE THREAD

**Issue by bvdbos** [mtudor/HomeySqueezebox#10]
With 0.2.0 : if I choose to add a device the app crashes:

In terminal : 

Error: Protocol "localhost:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:52:11)
    at Object.exports.request (http.js:31:10)
    at HttpClient._getRequestStream (/node_modules/jayson/lib/client/http.js:103:15)
    at /node_modules/jayson/lib/client/http.js:51:20
    at Object.Utils.JSON.stringify (/node_modules/jayson/lib/utils.js:298:3)
    at HttpClient._request (/node_modules/jayson/lib/client/http.js:37:14)
    at Client.request (/node_modules/jayson/lib/client.js:110:8)
    at SqueezeServer.SqueezeRequest.request (/node_modules/squeezenode/squeezerequest.js:53:16)
    at SqueezeServer.getPlayers (/node_modules/squeezenode/server.js:81:14)
    at register (/node_modules/squeezenode/server.js:90:14)

--- INFO: uk.co.icefusion.squeezebox has been killed ---

**Comment by mtudor** [comment]
Hi bvdbos,

Can you check that you have entered the server address of your Logitech Media Server in the app settings please?

We have a version coming that moves this setting to the pairing wizard to make it more obvious as a fair few people miss it at the moment.

Cheers!

Mark.

**Comment by bvdbos** [comment]
de-installed, rebooted Homey and re-installed. The same happens on pairing, before I can enter an ip... Did work before so suspect some install-leftover... 

So installed 0.0.2 instead of running. The same happened, then de-installed and rebooted... Tried from appstore 0.0.1 and github 0.0.2 but all the same...

**Comment by mtudor** [comment]
Hi again. Currently you have to enter the web address, including http, of the Logitech Media Server on the settings page before attempting to pair. It's in the COG section (Homey's settings) and not the DEVICES section where you will eventually pair.

**Comment by mtudor** [comment]
Have a look at "configure the app" under "getting started" on the main README.MD page of this github. Let me know if that solves it for you.

I agree it's not very intuitive at the moment but we haven't quite changed it yet.

**Comment by bvdbos** [comment]
Ah, that's it. Everytime i go to the settings-page there's no item/menu-option to enter settings for squeezebox but of course I go there when the app has crashed... Indeed, seems more like a device-thing to me (when using multiple servers) but that's could be done in the future...  👍 More tonight but I'll  cl;ose this one ...

**Comment by Inversion-NL** [comment]
Device settings is already done.
Just like auto discovery of the server through SSDP discovery (liked I showed you on Slack some time ago, remember? :-)

But we're currently restructuring the code. When that's done we'll start rolling out features gradually.

**Comment by bvdbos** [comment]
Well, if the crash for volume is gone, the first goal of the bounty is fulfilled:
https://forum.athom.com/discussion/2637/bounty-sending-audio-to-dlna-upnp-players

**Comment by mtudor** [comment]
@Inversion-NL Yep, sorry, that's what I meant :)

**Comment by Inversion-NL** [comment]
@mtudor Was not trying to correct you but rather trying to complement you, sorry. :-)
